accounts/urls.py
from django.urls import path, include, re_path
from . import views

app_name='accounts'

urlpatterns = [
    path('signup/', views.signup_view,name="signup"),
    path('login/', views.login_view,name="login"),
    path('logout/', views.logout_view,name="logout"),
]

articles/urls.py
from django.urls import path, include, re_path
from . import views

app_name='articles'

urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    re_path(r'^(?P<slug>[\w-]+)/$', views.article_detail,name="detail"),
]

helloworld/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('articles/',include('articles.urls')),
    path('', views.index),
    path('album/', views.photography),
    # path('messageboard/', view.messageboard),
]

urlpatterns += staticfiles_urlpatterns()

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=128, unique=True)
    slug = models.SlugField()
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    clap_num = models.IntegerField(default='0')
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.content[:50]+'...'


class Comment(models.Model):
    # post = models.ForeignKey('articles.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ["title","content","slug"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log the user in
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log in the user
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Article
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from . import forms
# Create your views here.

def article_list(request):
	articles = Article.objects.all().order_by('date')
	return render(request, 'articles/article_list.html',{'articles':articles})

# @login_required(login_url ="/accounts/login/")
def article_detail(request,slug):
	article = Article.objects.get(slug=slug)
	if request.method == 'POST':
		article.clap_num += 1
		article.save()
	return render(request,'articles/article_detail.html',{'article':article})

@login_required(login_url ="/accounts/login/")
def article_create(request):
	if request.method == 'POST':
		form = forms.CreateArticle(request.POST)
		if form.is_valid():
			#save article to db
			instance = form.save(commit=False)
			instance.author = request.user
			instance.save()
			return redirect('articles:list')
	else:
		form = forms.CreateArticle()
	return render(request,'articles/article_create.html',{'form':form})

helloworld/views.py
from django.shortcuts import render,redirect   # 加入 redirect 套件
from django.contrib.auth import authenticate
from django.contrib import auth
from django.http import HttpResponse
from django.contrib.auth.models import User
from os import listdir



def index(request):
  return render(request, 'home.html')

photo_count=[i+1 for i in range(4)]
def photography(request):
  return render(request, 'photography.html',{'photo_count': photo_count})

# def messageboard(request):
# 	return render_to_response('msgboard.html',locals())

accounts/templates/accounts/login.html
{% extends 'base_layout.html'%}

{% block content %}
  <h1>Login</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
  	{% csrf_token %}
  	{{ form }}
  	{% if request.GET.next %}
	  	<input type="hidden" name="next" value="{{request.GET.next}}">
  	{% endif %}
  	<input type="submit" value="Login">
  </form>
{% endblock%}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html'%}

{% block content %}
  <h1>Signup</h1>
  <form class="site-form" action="/accounts/signup/" method="post">
  	{% csrf_token %}
  	{{ form }}
  	<input type="submit" value="Signup">
  </form>
{% endblock%}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h2>Create an new article</h2>
        <form class="sitr-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{form}}
          <input type="submit" value="Create">
        </form>	
    </div>
{% endblock %}

articles/templates/articles/article_detail.html
<!DOCTYPE html>
<html lang="zh">
  {% load staticfiles %}
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Articles</title>
    <link href="{% static 'css/basic.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/article.css' %}" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <nav class="main-nav">
      <div class="full-wrapper">
        <div class="nav-logo-wrap">
          <div class="mobile-nav"></div>
          <div class="desktop-nav">
            <div class="primary-nav">
              <div class="menu-item">
                <a href="/">HOME</a>
              </div>
              <div class="menu-item">
                <a href="#">ABOUT</a>
              </div>
              <div class="menu-item">
                <a href="/articles/">BLOG</a>
              </div>
              <div class="menu-item">
                <a href="/album/">ALBUM</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <div class="article_detail">
      <div class="article">
        <h2>{{article.title}}</h2>
        <p>{{article.content}}</p>
        <p>{{article.date}}</p>
        <p>{{article.clap_num}}</p>
        <form action="" method="post">
          {% csrf_token %}
          {{ form }}
          <input type="submit" value='claaaap'>
        </form>
      </div>
    </div>
  </body>
</html

articles/templates/articles/article_list.html
{% extends 'base_layout.html'%}

{% block content %}
    <h1>Article List</h1>
    <div class="articles">
      {% for article in articles %}
      <div class="article">
        <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
        <p>{{article.snippet}}</p>
        <p>{{article.date}}</p>
      </div>
      {% endfor %}
    </div>
{% endblock%}

templates/base_layout.html
<!DOCTYPE html>
<html lang="zh">
  {% load staticfiles %}
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Articles</title>
    <link href="{% static 'css/basic.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/article.css' %}" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <nav class="main-nav">
      <div class="full-wrapper">
        <div class="nav-logo-wrap">
          <div class="mobile-nav"></div>
          <div class="desktop-nav">
            <div class="primary-nav">
              <div class="menu-item">
                <a href="/">HOME</a>
              </div>
              <div class="menu-item">
                <a href="#">ABOUT</a>
              </div>
              <div class="menu-item">
                <a href="{% url 'articles:list' %}">BLOG</a>
              </div>
              <div class="menu-item">
                <a href="/album/">ALBUM</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <ul>
        <li>
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit">Logout</button>
          </form>
        </li>
      </ul>
    </nav>
    {% block content %}
    {% endblock %}
  </body>
</html

templates/home.html
<!DOCTYPE html>
<html lang="zh">
{% load  staticfiles %}
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Bess</title>
    <link href="{% static 'css/basic.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/photography.css' %}" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lora" rel="stylesheet"/>
  </head>
  <body>
    <header>
      <div class="header-container">
        <div class="header-wrapper">
          <nav class="main-nav">                  
            <div class="mobile-nav"></div>
            <div class="desktop-nav">
              <div class="primary-nav">
                <div class="menu-item">
                  <a href="/">HOME</a>
                </div>
                <div class="menu-item">
                  <a href="#">WHO AM I</a>
                </div>
                <div class="menu-item">
                  <a href="/album/">PROJECT I DID</a>
                </div>
                <div class="menu-item">
                  <a href="/articles/">BLOG</a>
                </div>
                <div class="menu-item">
                  <a href="/album/">ALBUM</a>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </div>
    </header>
    <section class="homepageheader">
      <div class="homepageheader-text">
        <h3>This is</h3>
        <h1 class="myname">Bess</h1>
      </div>
    </section>
  </body>
</html>

templates/msgboard.html
<!DOCTYPE html>
<html lang="zh">
{% load  staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Week2Example留言板</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
  <div class="msgboard-container">
    <div class="board-header">
      <div class="board-title">
        <h1 id="title">到底要吃什麼</h1>   
      </div>
    </div>
    <div class="msgboard-content">
      <div class="msg-block otheruser-msgblock">
        <div class="msgcontent-container">
          <div class="user-name-block">
            <div class="user-name">QQ</div>
          </div>
          <div class="user-content-block">
            <div class="user-content">欸欸 午餐</div>
            <div class="content-time">Today 11:27</div>
          </div>
        </div>
      </div>
      <div class="msg-block otheruser-msgblock">
        <div class="msgcontent-container">
          <div class="user-name-block">
            <div class="user-name">RY</div>
          </div>
          <div class="user-content-block">
            <div class="user-content">不要辣! 其他我都可以</div>
            <div class="content-time">Today 11:28</div>
          </div>
        </div>
      </div>
      <div class="msg-block mine-msgblock">
        <div class="msgcontent-container">
          <div class="user-name-block">
            <div class="user-name">AB</div>
          </div>
          <div class="user-content-block">
            <div class="user-content">我要吃蘭州拉麵！</div>
            <div class="content-time">Today 11:32</div>
          </div>
        </div>
      </div>
    </div>
    <div class="msgboard-sendbox">
      <form action="" id="send-form">
        <input type="text" name="msg" id="msg-typing" placeholder="Type a message...">  
        <input type="submit" id="submit" value=">"> 
      </form>
    </div>
  </div>
</body>

templates/photography.html
<!DOCTYPE html>
<html lang="zh">
{% load staticfiles %}
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>攝影作品集</title>
    <link href="{% static 'css/photography.css' %}" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <!-- navagation-pannel -->
    <nav class="main-nav">
      <div class="full-wrapper">
        <div class="nav-logo-wrap">
          <div class="mobile-nav"></div>
          <div class="desktop-nav">
            <div class="primary-nav">
              <div class="menu-item">
                <a href="/">HOME</a>
              </div>
              <div class="menu-item">
                <a href="#">ABOUT</a>
              </div>
              <div class="menu-item">
                <a href="/articles/">BLOG</a>
              </div>
              <div class="menu-item">
                <a href="/album/">ALBUM</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <section class=title-section></section>
    <section class="main-section">
      <div class="container">
        <div class="row">
          {% for item in photo_count %}
          <div class="col">
            <img src="/static/images/{{item}}.jpg" alt="image">
          </div>
          {% endfor %}
        </div>
      </div>
    </section>
  </body>
</html>